### PR TITLE
Added pt-BR locale

### PR DESCRIPTION
**Pull request by vgrocha**
- Added pt-BR locale
- Some files had CR (Carriage Return) at the end of lines, some not. Following the Unix standard, the CRs were removed

### CODE REVIEW

**Comment by jbblanchet** [comment]
Hi,

Thanks for your pull request.

I won't be maintaining this repo. I don't even remember why I created it. If it's useful to you, I could transfer it, or you could clone it yourself. If not, I'll delete it next week.

**Comment by vgrocha** [comment]
Hey jbblanchet,
It was useful to me to create a template for formatting stuff in pt_BR.

You can transfer it to me. I'll take care of it.

Cheers!

**Comment by jbblanchet** [comment]
OK, I'll accept your pull request, then you'll have to delete your fork, and I'll transfer ownership of the repo.

**Comment by vgrocha** [comment]
Done! ready for docking! =)

**Pull request merged**
